/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as PreloadBreedsRouteImport } from './routes/_preloadBreeds'
import { Route as PreloadBreedsMatchmakingRouteImport } from './routes/_preloadBreeds/matchmaking'
import { Route as PreloadBreedsMarketingRouteImport } from './routes/_preloadBreeds/_marketing'
import { Route as PreloadBreedsMarketingIndexRouteImport } from './routes/_preloadBreeds/_marketing/index'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const PreloadBreedsRoute = PreloadBreedsRouteImport.update({
  id: '/_preloadBreeds',
  getParentRoute: () => rootRouteImport,
} as any)
const PreloadBreedsMatchmakingRoute =
  PreloadBreedsMatchmakingRouteImport.update({
    id: '/matchmaking',
    path: '/matchmaking',
    getParentRoute: () => PreloadBreedsRoute,
  } as any)
const PreloadBreedsMarketingRoute = PreloadBreedsMarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => PreloadBreedsRoute,
} as any)
const PreloadBreedsMarketingIndexRoute =
  PreloadBreedsMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PreloadBreedsMarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PreloadBreedsMarketingIndexRoute
  '/game': typeof GameRoute
  '/matchmaking': typeof PreloadBreedsMatchmakingRoute
}
export interface FileRoutesByTo {
  '/': typeof PreloadBreedsMarketingIndexRoute
  '/game': typeof GameRoute
  '/matchmaking': typeof PreloadBreedsMatchmakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_preloadBreeds': typeof PreloadBreedsRouteWithChildren
  '/game': typeof GameRoute
  '/_preloadBreeds/_marketing': typeof PreloadBreedsMarketingRouteWithChildren
  '/_preloadBreeds/matchmaking': typeof PreloadBreedsMatchmakingRoute
  '/_preloadBreeds/_marketing/': typeof PreloadBreedsMarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game' | '/matchmaking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/matchmaking'
  id:
    | '__root__'
    | '/_preloadBreeds'
    | '/game'
    | '/_preloadBreeds/_marketing'
    | '/_preloadBreeds/matchmaking'
    | '/_preloadBreeds/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PreloadBreedsRoute: typeof PreloadBreedsRouteWithChildren
  GameRoute: typeof GameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_preloadBreeds': {
      id: '/_preloadBreeds'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PreloadBreedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_preloadBreeds/matchmaking': {
      id: '/_preloadBreeds/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof PreloadBreedsMatchmakingRouteImport
      parentRoute: typeof PreloadBreedsRoute
    }
    '/_preloadBreeds/_marketing': {
      id: '/_preloadBreeds/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PreloadBreedsMarketingRouteImport
      parentRoute: typeof PreloadBreedsRoute
    }
    '/_preloadBreeds/_marketing/': {
      id: '/_preloadBreeds/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PreloadBreedsMarketingIndexRouteImport
      parentRoute: typeof PreloadBreedsMarketingRoute
    }
  }
}

interface PreloadBreedsMarketingRouteChildren {
  PreloadBreedsMarketingIndexRoute: typeof PreloadBreedsMarketingIndexRoute
}

const PreloadBreedsMarketingRouteChildren: PreloadBreedsMarketingRouteChildren =
  {
    PreloadBreedsMarketingIndexRoute: PreloadBreedsMarketingIndexRoute,
  }

const PreloadBreedsMarketingRouteWithChildren =
  PreloadBreedsMarketingRoute._addFileChildren(
    PreloadBreedsMarketingRouteChildren,
  )

interface PreloadBreedsRouteChildren {
  PreloadBreedsMarketingRoute: typeof PreloadBreedsMarketingRouteWithChildren
  PreloadBreedsMatchmakingRoute: typeof PreloadBreedsMatchmakingRoute
}

const PreloadBreedsRouteChildren: PreloadBreedsRouteChildren = {
  PreloadBreedsMarketingRoute: PreloadBreedsMarketingRouteWithChildren,
  PreloadBreedsMatchmakingRoute: PreloadBreedsMatchmakingRoute,
}

const PreloadBreedsRouteWithChildren = PreloadBreedsRoute._addFileChildren(
  PreloadBreedsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PreloadBreedsRoute: PreloadBreedsRouteWithChildren,
  GameRoute: GameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
